apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: root-certificate-2
  namespace: cert-manager
spec:
  isCA: true
  commonName: root-certificate-2
  secretName: root-secret-2
  duration: 219000h # about 25 years
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
