apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: root-certificate-2
  namespace: cert-manager
spec:
  isCA: true
  commonName: root-certificate-2
  secretName: root-secret-2
  duration: 219000h # about 25 years
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io

---

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: root-issuer-2
spec:
  ca:
    secretName: root-secret-2

---

apiVersion: policy.cert-manager.io/v1alpha1
kind: CertificateRequestPolicy
metadata:
  name: ca-issuer-policy-2
spec:
  allowed:
    isCA: false
    commonName:
      value: "*"
      required: true
    dnsNames:
      values:
      - "*"
      required: true
  constraints:
    maxDuration: 48h
  selector:
    issuerRef:
      name: root-issuer-2
      kind: ClusterIssuer
      group: cert-manager.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-manager-policy:ca-issuer-policy-2
rules:
  - apiGroups: ["policy.cert-manager.io"]
    resources: ["certificaterequestpolicies"]
    verbs: ["use"]
    # Name of the CertificateRequestPolicies to be used.
    resourceNames: ["ca-issuer-policy-2"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-policy:ca-issuer-policy-2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-policy:ca-issuer-policy-2
subjects:
- kind: Group
  name: system:authenticated
  apiGroup: rbac.authorization.k8s.io
