apiVersion: policy.cert-manager.io/v1alpha1
kind: CertificateRequestPolicy
metadata:
  name: ca-issuer-policy
spec:
  allowed:
    isCA: false
    commonName:
      value: "*"
      required: true
    dnsNames:
      values:
      - "*"
      required: true
  constraints:
    maxDuration: 48h
  selector:
    issuerRef:
      name: root-issuer
      kind: ClusterIssuer
      group: cert-manager.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-manager-policy:ca-issuer-policy
rules:
  - apiGroups: ["policy.cert-manager.io"]
    resources: ["certificaterequestpolicies"]
    verbs: ["use"]
    # Name of the CertificateRequestPolicies to be used.
    resourceNames: ["ca-issuer-policy"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-policy:ca-issuer-policy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-policy:ca-issuer-policy
subjects:
- kind: Group
  name: system:authenticated
  apiGroup: rbac.authorization.k8s.io
